version: "3.8"

services:
  # --- Databases ---
  user-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: userdb
    volumes:
      - user-db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - app-network

  address-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: addressdb
    volumes:
      - address-db-data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    networks:
      - app-network

  auth-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: authdb
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - app-network

  # --- Services ---
  auth-service:
    build: ./auth-service
    container_name: auth-service
    environment:
      - DB_HOST=auth-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=authdb
      - JWT_SECRET=verysecretkey
    depends_on:
      - auth-db
    ports:
      - "3002:3002" # HTTP
      - "50052:50052" # gRPC
    networks:
      - app-network

  user-service:
    build: ./user-service
    container_name: user-service
    environment:
      - DB_HOST=user-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=userdb
      - AUTH_GRPC_HOST=auth-service
      - AUTH_GRPC_PORT=50052
    depends_on:
      - user-db
      - auth-service
    ports:
      - "3001:3001" # HTTP
      - "50051:50051" # gRPC
    networks:
      - app-network

  address-service:
    build: ./address-service
    container_name: address-service
    environment:
      - DB_HOST=address-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=addressdb
      - USER_SERVICE_URL=http://user-service:3001
    depends_on:
      - address-db
      - user-service
    ports:
      - "3003:3003"
      - "50053:50053"
    networks:
      - app-network

  # --- API Gateway ---
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: on-failure
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - user-service
      - address-service
      - auth-service
    networks:
      - app-network

# --- Volumes ---
volumes:
  user-db-data:
  address-db-data:
  auth-db-data:

# --- Network ---
networks:
  app-network:
    driver: bridge
